FROM ubuntu:18.04

# install dependencies
RUN apt-get update
ENV DEBIAN_FRONTEND="noninteractive" TZ="Asia/Kolkata"
RUN apt-get install -y libopencv-dev liblinear-dev libsvm-dev libtiff5-dev

# SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Failed to execute child process ?dbus-launch? (No such file or directory)
RUN apt-get install dbus-x11

WORKDIR /home/ocr
